name: KinesteX_B2B
description: KinesteX SDK Demo
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  kinestex_sdk_flutter: ^1.0.7
  lottie: ^3.1.2
  intl: ^0.17.0
  cupertino_icons: ^1.0.8
  expandable_widgets: ^1.0.3
  #need to remove any
  provider: any
  # # KinesTex web view
  # kinestex_sdk_flutter: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/yoga_animation.json

  uses-material-design: true
